### ISSUE TITLE
versioning issue

### ISSUE THREAD

**Issue by IzzySoft** [Ruddle/RemoteCam#4]
I just noticed that the APKs from each release identify as

    package: name='com.samsung.android.scan3d' versionCode='1' versionName='1.0.0'

despite according to the tag names, none of them is v1.0.0 yet – and only one of them should be `versionCode='1'` (the first release ever). Could you please [take care for versioning](https://github.com/Ruddle/RemoteCam/blob/main/app/build.gradle#L30)? It's hard to tell the APKs apart, to know which one is installed – and with `versionCode` never being increased, for Android to decide if an APK contains an update (it argues it does not but is the very same version already installed, thus also no update notifications).

Thanks in advance!

**Comment by Ruddle** [comment]
I agree it is not clear as of now. 
By the way the reason the package name is com.samsung.android.scan3d is because Samsung only allow use of the telephoto camera to its own apps. So it is a kind of a cheat to reuse their package name. 
Ideally I would take a unique package name. I am all ears if anyone has a solution. 

I will post a new apk fixed soon, and keep taking care of versioning from now on.

**Comment by Ruddle** [comment]
1fe3196faa4b956606416139a7230d5c51faabf2

**Comment by IzzySoft** [comment]
Haha, you obviously already expected my next question – so I :bow: and thank you for answering before I asked it :rofl:

Wonderful, and thanks for fixing it that fast! Your app will [become available here](https://apt.izzysoft.de/packages/com.samsung.android.scan3d/) in less than 2 hours from now (with the next sync around 6 pm UTC). Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there e.g. from your Readme!
